from attrdict.mixins import MutableAttr
from typing import Any, Optional


class AttrMap(MutableAttr):
    def __init__(self, items: Optional[Any] = ..., sequence_type: Any = ...) -> None: ...

    def __getitem__(self, key: Any): ...

    def __setitem__(self, key: Any, value: Any) -> None: ...

    def __delitem__(self, key: Any) -> None: ...

    def __len__(self): ...

    def __iter__(self) -> Any: ...
